### ISSUE TITLE
Refresh OSCD website content

### ISSUE THREAD

**Issue by aw350m33d** [oscd-initiative/oscd-task-management#1]
Refresh OSCD [website](https://oscd.community/) content
- [x] results 
- [x] "last sprint participants" list 
- [x] links
- [x] 3rd sprint placeholder
- [x] Navigator layers version

**Comment by zinint** [comment]
Fixed Navigator layers version error.

**Comment by zinint** [comment]
I forked the site and started making changes, will create PR to oscd-initiative/oscd soon.

**Comment by zinint** [comment]
https://github.com/oscd-initiative/oscd/pull/4
