### ISSUE TITLE
Merge TheHive's Cortex analyzers `feature/oscd` branch to the `master`

### ISSUE THREAD

**Issue by aw350m33d** [oscd-initiative/oscd-task-management#3]
Merge TheHive's [Cortex-Analyzers](https://github.com/TheHive-Project/Cortex-Analyzers) `feature/oscd` branch to the `master`
- [x] Create final PR
- [x] Fix issues
- [x] Ask for merge

**Comment by yugoslavskiy** [comment]
It's done (:
